### ISSUE TITLE
IntelliJ 2024.1

### ISSUE THREAD

**Issue by CLOVIS-AI** [google/coroutine-stacks#5]
Please add support for IntelliJ 2024.1 :pray:

**Comment by nikita-nazarov** [comment]
Hi @CLOVIS-AI! Sorry for the late reply, I was vacationing. I've pushed an update and now the JetBrains team has to approve it.

**Comment by CLOVIS-AI** [comment]
No problem, enjoy your vacations!

I'm on build #IU-241.15989.69 now, though :sweat_smile:

**Comment by nikita-nazarov** [comment]
You can now update to the compatible version!

**Comment by nikita-nazarov** [comment]
> I don't know anything about plugin development, so I'm kinda curious—is it standard practice to declare a maximum version, and manually update it on each new IntelliJ version?

Unfortunately yes. Because of deprecated apis. Suppose version X uses some old api which was deprecated in Y and removed in Z. When the Z version is released you have to rewrite your code and as a result the new version of your plugin is compatible with Z but not compatible with X.

**Comment by nikita-nazarov** [comment]
By the way, if you have any feedback about the plugin I would be very happy if you shared it! It will help me understand how to improve the plugin.

**Comment by CLOVIS-AI** [comment]
Finally managed to give it a try and… wow I don't think I'll be able to live without it now :sweat_smile: amazing plugins, thanks a lot!

**Comment by nikita-nazarov** [comment]
Thanks for your feedback! I'm glad you liked it!
