### ISSUE TITLE
Support K2 mode

### ISSUE THREAD

**Issue by dkuznetsov-aligntech** [google/coroutine-stacks#6]
As JetBrains is preparing to enable the new K2 Kotlin compiler mode in Intellij Idea by the end of 2024 (currently in Beta):
https://blog.jetbrains.com/idea/2024/03/k2-kotlin-mode-alpha-in-intellij-idea/
https://blog.jetbrains.com/idea/2024/05/intellij-idea-2024-2-eap-2/

It would be great to see this plugin support K2 mode as well, since currently the plugin is not loaded if K2 mode is enabled in intellij idea. Once the new mode becomes the default, this plugin will be impossible to use, unfortunately.

**Comment by nikita-nazarov** [comment]
Hi @dkuznetsov-aligntech! Thanks for opening an issue about it. As the blog post that you shared says:

> Third-party IntelliJ IDEA plugins depending on the Kotlin plugin will be disabled. We will provide migration guidance for third-party plugin authors soon! 

The migration guide is not out yet, but once it is I will update the plugin!

**Comment by nikita-nazarov** [comment]
The K2 is now supported in Coroutine Stacks 1.0.3!
